### ISSUE TITLE
Fix design

### ISSUE THREAD

**Issue by kylecarbs** [nhooyr/blog#22]
Looks bad atm.

**Comment by nhooyr** [comment]
Very true, it sucks.

**Comment by nhooyr** [comment]
https://5e1b267986c2ed0007a39a41--nhooyr.netlify.com

Thoughts now?

**Comment by kylecarbs** [comment]
Oh wow 👀 only bug is the active state for “Posts” underlines it

**Comment by nhooyr** [comment]
Fixed. Ty sir <3

**Comment by nhooyr** [comment]
https://5e1e98ad75441600087b9449--nhooyr.netlify.com/why
